kegiatan/urls.py
from django.urls import path

from .views import list_kegiatan,tambah_peserta,tambah_kegiatan

app_name = 'Kegiatan'


urlpatterns = [

    path('', list_kegiatan , name = 'list'),
    path('tambahpeserta', tambah_peserta, name = 'tambahpeserta'),
    path('tambahkegiatan', tambah_kegiatan, name = 'tambahkegiatan'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from Story9 import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('kegiatan/', include('kegiatan.urls', namespace = 'templates')),
    path('Story7/', include(('Story7.urls','Story7'), namespace = 'Story7')),
    path('Story8/', include(('Story8.urls','Story8'), namespace = 'Story8')),
    path('login/', v.loginPage, name='login'),
    path('logout/', v.logoutUser, name='logout'),
    path('register/', v.register, name='register'),
    path('', include("django.contrib.auth.urls")),
]

kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan= models.CharField(max_length=30)
    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan,null = True, on_delete= models.SET_NULL)

    def __str__(self):
        return self.nama_peserta

# class Publication(models.Model):
#     title = models.CharField(max_length=30)

#     class Meta:
#         ordering = ['title']

#     def __str__(self):
#         return self.title

# class Article(models.Model):
#     headline = models.CharField(max_length=100)
#     publications = models.ManyToManyField(Publication)

#     class Meta:
#         ordering = ['headline']

#     def __str__(self):
#         return self.headline

kegiatan/forms.py
from django import forms
from .models import Kegiatan, Peserta

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields ="__all__"
    

class formPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = "__all__"

kegiatan/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan,Peserta
from .forms import formKegiatan,formPeserta


# Create your views here.
def list_kegiatan(request):
    list_kegiatan = Kegiatan.objects.all()
    data_kegiatan = []
    for kegiatan in list_kegiatan:
        list_peserta = Peserta.objects.filter(kegiatan=kegiatan)
        data_peserta = []
        for peserta in list_peserta:
            data_peserta.append(peserta)
        data_kegiatan.append((kegiatan,data_peserta))
    context = {'data_kegiatan':data_kegiatan,'number':5}
    return render(request,'kegiatan.html',context)



def tambah_peserta(request):
    form = formPeserta()
    if (form.is_valid and request.method == 'POST'):
        form = formPeserta(request.POST)
        form.save()
        return redirect('/kegiatan')
    context = {'form':form,'number':5}
    return render(request,'tambahpeserta.html',context)

def tambah_kegiatan(request):
    form = formKegiatan()
    if (form.is_valid and request.method == 'POST'):
        form = formKegiatan(request.POST)
        form.save()
        return redirect('/kegiatan')

    context = {'form':form,'number':5}
    
    return render(request,'tambahkegiatan.html',context)

kegiatan/templates/kegiatan.html
<!doctype html>
<html lang="en">
  {% extends "base.html" %}
  {% load static %}
  {% block content %}

  <style>
    body{
        background:url("/static/ggwp.jpeg") no-repeat;
        padding-bottom: 65vw;
        background-size: cover;
        font-family: Arial, Helvetica, sans-serif;
    }
  </style>
  
  <main>
    <div style="margin: 90px">
    <section class="section-1">
        
      <div class = "container text-center">
        <div class="text-left"><a class="btn btn-sm btn-dark" href="tambahkegiatan">Tambah Kegiatan</a></div>
        <h1 class="text-center">
            Daftar Kegiatan
        </h1>
          <div class="row">

            {% for i in data_kegiatan %}
              <div class="card" style="width: 100%;">
                  <div class="card-body">
                    
                    <h5 class="card-title mb-3">{{i.0.nama_kegiatan}}</h5>
                    <p class="card-text">
                        {% for a in i.1 %}
                        <div>{{a.nama_peserta}}</div>
                        {% endfor %}
                        </p>
                        
                        
                </div>
          </div>
          {% endfor %}
          
        </div>
        <br>
        <div class="text-center"><a class="btn btn-sm btn-dark" href="{% url 'templates:tambahpeserta' %}">Tambah Peserta</a></div>
        <br><br><br><br><br><br>
    </div>
    </section>
    </div>
</div>
    
  </main>
  {% endblock %}

kegiatan/templates/tambahkegiatan.html
{% extends "base.html" %}
  {% load static %}
  {% block content %}
<form action="" method="post">
  <style>
    body{
        background:url("/static/ggwp.jpeg") no-repeat;
        padding-bottom: 65vw;
        background-size: cover;
        font-family: Arial, Helvetica, sans-serif;
    }
  </style>
  <div style="margin: 100px">
    {% csrf_token %}
{{form}}
<input id="submit" type="submit" class="btn btn-lg btn-block btn-dark" value="Tambah">
<a class="btn btn-lg btn-block btn-dark" href="/kegiatan">Batal</a>
</form>
</div>
{% endblock %}

kegiatan/templates/tambahpeserta.html
<form action="" method="post">
    <style>
        body{
            background:url("/static/ggwp.jpeg") no-repeat;
            padding-bottom: 65vw;
            background-size: cover;
            font-family: Arial, Helvetica, sans-serif;
        }
      </style>
    <div style="margin: 20px">
    {% csrf_token %}
{{form}}
<input id="submit" type="submit" class="btn btn-lg btn-block btn-dark" value="Tambah">
</div>
</form>