Story7/urls.py
from django.urls import path
from .views import index
from . import views


appname = 'Story7'

urlpatterns = [
   path('', views.index, name = 'accordion'),
]

Story8/urls.py
from django.urls import path
from .views import cari, search
from . import views

app_name = 'Story8'

urlpatterns = [
    path('', views.cari, name='cari'),
    path('buku/<str:key>', views.search, name='search'),
]

homepage/urls.py
from django.urls import path
from .views import Join, sched_delete, detail
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('biodata/', views.bio, name='bio'),
    path('studies/', views.studies, name='studies'),
    path('about/', views.about, name='about'),
    path('socmed/', views.socmed, name='socmed'),
    path('story1/', views.story1, name='story1'),
    path('Schedule/', views.Join, name='Schedule'),
    path('<int:pk>', sched_delete, name ='Delete'),
    path('detail/<int:pk>', views.detail, name ='Detail'),
]

kegiatan/urls.py
from django.urls import path

from .views import list_kegiatan,tambah_peserta,tambah_kegiatan

app_name = 'Kegiatan'


urlpatterns = [

    path('', list_kegiatan , name = 'list'),
    path('tambahpeserta', tambah_peserta, name = 'tambahpeserta'),
    path('tambahkegiatan', tambah_kegiatan, name = 'tambahkegiatan'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from Story9 import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('kegiatan/', include('kegiatan.urls', namespace = 'templates')),
    path('Story7/', include(('Story7.urls','Story7'), namespace = 'Story7')),
    path('Story8/', include(('Story8.urls','Story8'), namespace = 'Story8')),
    path('login/', v.loginPage, name='login'),
    path('logout/', v.logoutUser, name='logout'),
    path('register/', v.register, name='register'),
    path('', include("django.contrib.auth.urls")),
]

homepage/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    Matkul = models.CharField(max_length=50)
    Dosen = models.CharField(max_length=50)
    SKS = models.CharField(max_length=50)
    Deskripsi = models.CharField(max_length=50)
    Semester = models.CharField(max_length=50) 
    Ruang = models.CharField(max_length=50)
    
    # Day = models.CharField(max_length=50)
    # Date = models.DateField(blank = False)
    # Time = models.TimeField()
    # Name = models.TextField(max_length=50)
    # Location = models.TextField(max_length=50)
    # Category = models.TextField(max_length=50)

homepage/forms.py
from django import forms

class SchedForm(forms.Form):

    Matkul = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Mata Kuliah',
        'type' : 'text',
        'required': True,
    }))

    Dosen = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Dosen',
        'type' : 'text',
        'required': True,
    }))

    SKS = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jumlah SKS',
        'type' : 'text',
        'required': True,
    }))

    Deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Deskripsi',
        'type' : 'text',
        'required': True,
    }))

    Semester = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Semester Tahun',
        'type' : 'text',
        'required': True,
    }))

    Ruang = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Ruang',
        'type' : 'text',
        'required': True,
    }))



    # Day = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Day',
    #     'type' : 'text',
    #     'required': True,
    # }))

    # Date = forms.DateField(widget=forms.DateInput(attrs={
    #     'class': 'form-control',
    #     'placeholder' : 'dd/mm/yyyy',
    #     'type' : 'date',
    #     'required': True,
    # }))

    # Time = forms.TimeField(widget=forms.TimeInput(attrs={
    #     'class': 'form-control',
    #     'type' : 'time',
    #     'required': True,
    # }))

    # Name = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type' : 'text',
    #     'placeholder': 'Activity Name',
    #     'required': True,
    # }))

    # Location = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type' : 'text',
    #     'placeholder': 'Activity Location',
    #     'required': True,
    # }))

    # Category = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type' : 'text',
    #     'placeholder': 'Activity Type',
    #     'required': True,
    # }))

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule as jadwal
from .forms import SchedForm


# Create your views here.
def index(request):
    return render(request, 'index.html')

def bio(request):
    return render(request, 'bio.html')

def studies(request):
    return render(request, 'studies.html')

def about(request):
    return render(request, 'about.html')

def socmed(request):
    return render(request, 'socmed.html')

def story1(request):
    return render(request, 'story1.html')

def Join(request):
    form = SchedForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            sched = jadwal()
            sched.Matkul = form.cleaned_data['Matkul']
            sched.Dosen = form.cleaned_data['Dosen']
            sched.SKS = form.cleaned_data['SKS']
            sched.Deskripsi = form.cleaned_data['Deskripsi']
            sched.Semester = form.cleaned_data['Semester']
            sched.Ruang = form.cleaned_data['Ruang']
            # sched.Day = form.cleaned_data['Day']
            # sched.Date = form.cleaned_data['Date']
            # sched.Time = form.cleaned_data['Time']
            # sched.Name = form.cleaned_data['Name']
            # sched.Location = form.cleaned_data['Location']
            # sched.Category = form.cleaned_data['Category']
            sched.save()
            return redirect('/Schedule')
    
    sched = jadwal.objects.all()
    form = SchedForm()
    response = {"sched":sched, 'form' : form}
    return render(request,'Schedule.html',response)

def sched_delete(request, pk):
    form = SchedForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            sched = jadwal()
            sched.Matkul = form.cleaned_data['Matkul']
            sched.Dosen = form.cleaned_data['Dosen']
            sched.SKS = form.cleaned_data['SKS']
            sched.Deskripsi = form.cleaned_data['Deskripsi']
            sched.Semester = form.cleaned_data['Semester']
            sched.Ruang = form.cleaned_data['Ruang']
            # sched.Day = form.cleaned_data['Day']
            # sched.Date = form.cleaned_data['Date']
            # sched.Time = form.cleaned_data['Time']
            # sched.Name = form.cleaned_data['Name']
            # sched.Location = form.cleaned_data['Location']
            # sched.Category = form.cleaned_data['Category']
            sched.save()
            return redirect('/Schedule')
    
    jadwal.objects.filter(pk=pk).delete()
    data = jadwal.objects.all()
    form = SchedForm()
    response = {"sched":data, 'form' : form}
    return render(request, 'Schedule.html', response)

def detail(request, pk):
    sched = jadwal.objects.all().filter(id=pk)
    response = {"SchedForm" : sched}
    return render(request, "detail.html", response)
    

homepage/templates/Schedule.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<body>
    <style>
        body{
            background:url("/static/ggwp.jpeg");
            padding-bottom: 65vw;
            background-size: cover;
            font-family: Arial, Helvetica, sans-serif;
        }
        </style>
<div style="margin: 55px"> 
    <div id = "Salam">
            <h1>My Schedule</h1>
        </div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <form action='' method="POST">
                        {% csrf_token %}
                        {{ form }}
                    <div class="centre-items">
                        <input type="submit" class="btn btn-primary" value="Add Schedule">
                    </div>
                    </form>
                </div>
                <div class="col" id="tulisan">
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Matkul</th>
                            <th scope="col">Dosen</th>
                            <th scope="col">SKS</th>
                            <th scope="col">Deskripsi</th>
                            <th scope="col">Semester</th>
                            <th scope="col">Ruang</th>
                            <th scope="col">Delete</th>
                            <!-- <th scope="col">Day</th>
                            <th scope="col">Date</th>
                            <th scope="col">Time</th>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Location</th>
                            <th scope="col">Delete</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for jadwal in sched %}
                                <tr>
                                <th scope="row"><a href="{% url 'homepage:Detail' jadwal.id %}">{{jadwal.Matkul}}</a></th>
                                <td>{{jadwal.Dosen}}</td>
                                <td>{{jadwal.SKS}}</td>
                                <td>{{jadwal.Deskripsi}}</td>
                                <td>{{jadwal.Semester}}</td>
                                <td>{{jadwal.Ruang}}</td>
                                <!-- <th scope="row">{{jadwal.Day}}</th>
                                <td>{{jadwal.Date}}</td>
                                <td>{{jadwal.Time}}</td>
                                <td>{{jadwal.Name}}</td>
                                <td>{{jadwal.Category}}</td>
                                <td>{{jadwal.Location}}</td> -->
                                <td><a href="{% url 'homepage:Delete' jadwal.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
         </div>
    </body>

{% endblock %}

homepage/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

      <style>
      body{
          background:url("/static/about1.jpeg") no-repeat;
          padding-bottom: 65vw;
          background-size: cover;
          font-family: Arial, Helvetica, sans-serif;
      }
      </style>
  
    <div style="margin: 100px">  
      <h1 class="about">ABOUT ME</h1>   
      <br>
      <h3 class="about1">Halo Semuanya perkenalkan nama saya Martua Reynard
      William Pasaribu, saya adalah mahasiswa aktif dari
      Universitas Indonesia. Saya membuat website ini dengan
      tujuan untuk dapat saling berbagi informasi ataupun banyak
      hal lain yang bermanfaat yang dapat saya bagikan.</h3>
    </div>

{% endblock %}

homepage/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Martua Reynard William Pasaribu</title>
  </head>
  <body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="main-nav">
        <div class="container">
        <a class="navbar-brand" href="#page-top">PPW</a>
        {% if user.is_authenticated %}
        Hello  {{request.user}}
        {% endif %}
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage:bio' %}">Biodata</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage:studies' %}">Studies</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'homepage:about' %}">About Me</a>
              </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'homepage:socmed' %}">Social Media</a>
              </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'homepage:story1' %}">Story 1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'homepage:Schedule' %}">Schedule</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'templates:list' %}">Kegiatan</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'Story7:accordion' %}">Story7</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'Story8:cari' %}">Story8</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}">Log out</a>
            </li> 
            {% else %}
            <li class="nav-item {% if number == 8 %} active {% endif %}">
              <a class="nav-link js-scroll-trigger" href="{% url 'login' %}">Log in</a>
            </li> 
            {% endif %}
          </ul>
        </div>
        </div>
      </nav>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

      {% block content %}

      {% endblock %}
    </body>
    </html>

homepage/templates/bio.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  
    <style>
        body{
            background:url("/static/bio.jpeg") no-repeat;
            padding-bottom: 65vw;
            background-size: cover;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
  
    
    <div style="margin: 100px">  
      <h1 class="bio">BIODATA</h1>
      <br>
      <h3 class="bio1">Nama: Martua Reynard William Pasaribu</h3>
      <h3 class="bio1">NPM: 1906400210</h3>
      <h3 class="bio1">Angkatan: 2019</h3>
      <h3 class="bio1">Pekerjaan: Mahasiswa</h3>
      <h3 class="bio1">Tempat Kuliah: Universitas Indonesia</h3>
    </div>
    </div>

{% endblock %}

homepage/templates/detail.html
<html lang="en"><head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detail Mata Kuliah</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|PT+Serif:400,700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/home/style2.css">
    <link rel="stylesheet" href="../../static/home/mobile-style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    
</head>

<body>
    <div class="main-content">
        


<link rel="stylesheet" href="/static/home/Story5.css">

<style>
    body{
        background:url("/static/salju.jpeg");
        padding-bottom: 65vw;
        background-size: cover;
        font-family: Arial, Helvetica, sans-serif;
    }
    </style>

    <div class="container">
        <h1 class="text-center">
             Detail Mata Kuliah
        </h1>
        <p>
            
        </p>
    <br>
    <table class="table table-striped table-dark">
        {% for Matkul in SchedForm %}
            <tbody><tr>
                <td id="detail_matkul_keterangan">Nama Matkul</td>
                <td id="detail_matkul_penjelasan">{{Matkul.Matkul}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Nama Dosen</td>
                <td id="detail_matkul_penjelasan">{{Matkul.Dosen}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Jumlah SKS</td>
                <td id="detail_matkul_penjelasan">{{Matkul.SKS}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Deskripsi</td>
                <td id="detail_matkul_penjelasan">{{Matkul.Deskripsi}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Semester</td>
                <td id="detail_matkul_penjelasan">{{Matkul.Semester}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Nomor Ruangan</td>
                <td id="detail_matkul_penjelasan">{{Matkul.Ruang}}</td>
            </tr>
        </tbody>
        {% endfor %}
        </table>
      <div class="text-center">
        <a class="btn btn-sm btn-dark" href="/Schedule">Kembali</a>
      </div>
    </div>


    </div>

    
    



    
    




</body></html>

homepage/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <style>
        body{
            background:url("/static/home1.jpeg");
            padding-bottom: 65vw;
            background-size: cover;
            font-family: Arial, Helvetica, sans-serif;
        }
        </style>
    
    <div>
        <img class="rey" src="/static/REY.png" alt="centered image" />
        <h1 class="text1">Welcome To</h1>
        <h1 class="text2">My Website!</h1>
    </div>
    <style>
        .rey {
            margin: 150px auto 100px;
            display: block;
        }
        </style>


{% endblock %}

homepage/templates/socmed.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <style>
      body{
          background:url("/static/gg.jpeg") no-repeat;
          padding-bottom: 65vw;
          background-size: cover;
          font-family: Arial, Helvetica, sans-serif;
      }
    </style>

    <div style="margin: 100px">
    <h1 class="socmed">SOCIAL MEDIA</h1>
    <br>
    <a class="socmed1" href="https://www.instagram.com/reeyy17/"><img src="/static/ig.jpeg" width="50" height="50"></a>
    <a class="socmed1" href="https://www.facebook.com/athalla.layadi"><img src="/static/fb.png" width="50" height="50"></a>

    {% endblock %}

homepage/templates/story1.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <head>
    <title>My Profile</title>
    <style>
        table, th, td {
              border: 2px solid black;
        }
    </style>
</head>
<body>
    <div style="margin: 50px">  
    <h1 allign="justify"> My Profile </h1>

    <a href="https://ibb.co/kMcVxzG"><img class= "pas-foto" src="https://i.ibb.co/nRkqb4w/mk.jpg" alt="mk" border="0"></a>
    <p> <b> Nama </b>: Martua Reynard William Pasaribu</p>
    <p> <b> NPM </b>: 1906400210</p>
    <p> <b> Angkatan </b>: 2019</p>
    <p> <b> Tempat Kuliah </b>: Universitas Indonesia</p>
    <p> <b> Hobi </b>: Nonton Film, Bermain games, Olahraga</p>
    <p> <b> Deskripsi tentang saya </b>: Saya adalah orang yang sangat suka melakukan hal yang baru yang belum pernah saya lakukan sebelumnya, saya juga sangat suka berolahraga dan bermain game serta saya berharap dapat mendapatkan banyak ilmu di fasilkom.</p>
    <p> <b> Media Sosial </b>:</p>
    <li>Line : martua17 </li>
    <li>Instagram : reeyy17</li>
    <p> <b> Riwayat Pendidikan </b></p>
     <table>
        <tbody><tr>
            <th> <b> Tahun </b> </th>
            <th> <b> Nama Sekolah </b> </th>
        </tr>
        <tr>
            <td> 2019-Sekarang </td>
            <td> Universitas Indonesia </td>
        </tr>
        <tr>
            <td> 2016-2019 </td>
            <td> SMA Budhaya II Santo Agustinus </td>
        </tr>
        <tr>
            <td> 2013-2016 </td>
            <td> SMP Xaverius Lubuklinggau </td>
        </tr>
        <tr>
            <td> 2007-2013 </td>
            <td> SD Xaverius Lubuklinggau </td>
        </tr>
    </tbody></table>


</body>

{% endblock %}

homepage/templates/studies.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <style>
      body{
          background:url("/static/education.jpeg") no-repeat;
          padding-bottom: 40vw;
          background-size: cover;
          font-family: Arial, Helvetica, sans-serif;
      }
    </style>
  
    <div style="margin: 100px">
      <h1 class="studies">STUDIES</h1>    
      <br>
      <h3 class="studies1">Universitas Indonesia</h3>
      <h3 class="studies1">SMA Budhaya II Santo Agustinus</h3>
      <h3 class="studies1">SMP Xaverius Lubuklinggau</h3>
      <h3 class="studies1">SD Xaverius Lubuklinggau</h3>
    </div>

    {% endblock %}